config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :transactions
  devise_for :users
  resources :comments
  resources :items
  resources :charges

  # Lendr: Added routes manually as controllers and models were generated not using scaffolding.
  root 'pages#welcome'
  get 'dashboard', to: 'pages#dashboard'
  # get 'categories', to: 'categories#index'
  # get 'categories/:id', to: 'categories#show'
  # get 'transactions', to: 'transactions#index'
  # get 'transactions/:id', to: 'transactions#show'

end

app/models/item.rb
class Item < ApplicationRecord
    # Lendr: Establishes association - an item belongs to single user, a single category and multiple images, and is associated with many transactions and comments.
    belongs_to :user, required: false
    belongs_to :category, required: false
    has_many :transactions
    has_many_attached :images
    has_many :comments 

    # Lendr: Add validations to ensure required data must be entered by user when creating a new item
    validates :name, presence: true
    validates :category, presence: true
    validates :description, presence: true
    validates :price, presence: true

    private
    def image_type
        if image.attached? == false
            errors.add(:images, 'are missing, please add photo(s) of your listed item.')
        end
    end 

    def self.search(search)
        if search
            where("name iLIKE ? OR description LIKE ?", "%#{search}%", "%#{search}%") 
        else
            all
        end
    end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # Lendr: Items created using scaffolding.
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.search(params[:search])
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
    # Lendr: Pundit authorisation for item
    authorize @item
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)
    # Lendr: Sets the seller of a new Item listing to current user.
    @item.user = current_user
    # Lendr: When a new Item is created, it assigns the Category to the Category FK in the Item database.
    category = Category.find(params[:item][:category_id])
    @item.category = category
    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    # For Pundit authorisation
    authorize @item
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      # Lendr: Add :image as a permitted param for all other CRUD methods in Items to refer back to.
      result = params.require(:item).permit(:name, :description, :terms, :price, :street, :suburb, :state, :postcode, :next_available, images: [])
      # Lendr: So that resulting price will be converted to float.
      result[:price] = result[:price].to_f * 100.0
      result
    end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<h2>NEW.</h2>

<div class="item-form">

  <%= form_with(model: item, local: true) do |form| %>

    <% if item.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

        <ul>
        <% item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <br><br>

    <%# Lendr: Create a new custom form collection field Category, add dropdown menu. %>
    <div class="field">
      <%= form.collection_select :category_id, Category.order(:name), :id, :name, include_blank: false, prompt: "Select a category" %>
      <div style="clear:both;"></div>
    </div>

    <br>

    <%# Lendr: Update custom form text field Name %>
    <div class="field">
      <%= form.text_field :name, size: "50", required: true %>
      <%= form.label :item_name %>
    </div>


    <%# Lendr: Add custom form text area field for Description %>
    <div class="field">
      <%= form.text_area :description, placeholder: "A short description of the item you would like to lend.", size: "50x3",  required: true  %>
      <%= form.label :description %>

    </div>
    
    <%# Lendr: Add custom form text area field for Terms and Conditions %>
    <div class="field">
      <%= form.text_area :terms, placeholder: "You may clarify your terms and conditions for lending out this listed item (E.g. minimum days to be rented to condition/ condition befoe return).", size: "50x3",  required: true %>
      <%= form.label :terms_and_conditions %>

    </div>

    <%# Lendr: Add custom form file field for Image, allow for multiple images to be uploaded. %>
    <div class="field">
      <p>
        <%= form.label :images %>
          <small>(You may select multiple images to upload, file formats must be: jpeg, gif, png, bmp)</small>
      </p>
      <%= form.file_field :images, multiple: true, accept: 'image/png,image/gif,image/jpeg,image/bmp' %>
    </div>

      
    <%# Lendr: Add formatting to display form text field for Price correctly %>
    <div class="field">
      <%= form.number_field :price, value: number_with_precision((item.price||0)/100.0, :precision => 2), step: :any,  required: true %>
      <%= form.label :price_per_day, value: '' %>
    </div>

    <div class="field">
      <%= form.text_field :street,  required: true %>
      <%= form.label :street %>
    </div>

    <div class="field">
      <%= form.text_field :suburb,  required: true %>
      <%= form.label :suburb %>
    </div>

    <div class="field">
      <%= form.text_field :state,  required: true %>
      <%= form.label :state %>
    </div>

    <div class="field">
      <%= form.text_field :postcode,  required: true %>
      <%= form.label :postcode %>
    </div>

    <%# Lendr: Add custom form date field for Next Available status displayed by day, month, year  %>
    <div class="field">
      <%= form.text_field :next_available, :data => {:theme =>'lendr-calendar'}, class: 'calendar',  required: true %>
      <%= form.label :next_available %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<br><br>

<h1>ITEMS</h1>

<br><br>

<div>
</div>

<table class="index-table">
  <thead class="index-table-head">
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th>Description</th>
      <th>Terms</th>
      <th>Price</th>
      <th>Suburb</th>
      <th>State</th>
      <th>Availablity</th>
      <th>Next Available</th>
      <th>Preview</th>
      <th colspan="3">Action Links</th>
    </tr>
  </thead>

  <tbody class="index-table-body">
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= link_to item.category.name, item.category %></td>
        <td><%= item.description %></td>
        <td><%= item.terms %></td>
        <td><%= number_to_currency(item.price/100.0) %></td>
        <td><%= item.suburb %></td>
        <td><%= item.state %></td>
        <td>
          <% if item.next_available < Time.now %>
            <strong>AVAILABLE!</strong>
            <% else %>
            <strong>UNAVAILABLE!</strong>
          <% end %>
        </td>
        <td><%= item.next_available.strftime('%a, %e %b %Y') %></td>
        <td><%= image_tag item.images.first, height: '80'%></td> 
        <td><%= link_to 'Show', item %></td>

        <% if item.user == current_user %>  
          <td><%= link_to 'Edit', edit_item_path(item) %></td>
          <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/items/new.html.erb
<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.css" />

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick-theme.css" />

<p id="notice"><%= notice %></p>

<h1>Item Listing</h1>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @item.category.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Terms:</strong>
  <%= @item.terms %>
</p>

<div class="image-slider">
  <% @item.images.each do |image| %>
    <div>
      <%= image_tag(image, height: '400') %>
    </div>
  <% end %>
</div>

<p>
  <strong>Price:</strong>
  <%= number_to_currency(@item.price/100.0) %>
</p>

<p>
  <strong>Suburb:</strong>
  <%= @item.suburb %>
</p>

<p>
  <strong>State:</strong>
  <%= @item.state %>
</p>

<br><br>

<h2>RENT NOW.</h2>

<% if user_signed_in? %> 
  <% if @item.next_available < Time.now %>
    <strong>AVAILABLE: This listing is available for rent now!</strong>

    <br><br>

      <%= form_tag charges_path do %>
        <article>
          <% if flash[:error].present? %>
            <div id="error_explanation">
              <p><%= flash[:error] %></p>
            </div>
          <% end %>
        </article>
        <%= hidden_field_tag(:item_id, @item.id) %>
        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                data-description="<%= @item.name %>"
                data-amount="<%= @item.price %>"
                data-currency="AUD"
                data-locale="auto"></script>
      <% end %>

    <% else %>
    <strong>UNAVAILABLE: This listing is unfortunately unavailable for rent at the moment.</strong>
  <% end %>
  <% else %>
  <br><br>
  <strong>Sign Up or Login to rent this item!</strong>
<% end %>
<br><br>
<hr>
<br>

<h3>COMMENTS</h3>

<p>
  <% @item.comments.each do |comment| %>
    <div>
      <%= comment.review %>
      <p><em>Rating: <strong><%= comment.rating %></strong></em></p>
      <p><em> posted by <strong><%= comment.user.email %> </strong></em></p>
      <hr>
    </div>
  <% end %>
</p>


<br><br>
<% if @item.user == current_user %>  
  <%= link_to 'Edit', edit_item_path(@item) %> |
<% end %>
<%= link_to 'Back', items_path %>